### ISSUE TITLE
Restore position after whitespace trim

### ISSUE THREAD

**Issue by matteo-briani** [johnfrankmorgan/whitespace.nvim#6]
Hi, thanks for this useful plugin! 
I have a request/question to ask.

The trim function leave the cursor on the last trimmed white-space. 
I can jump back to the last position with a quick hit of `''`, so not a big deal after all.
However, would it be possible to add an optional behavior to automatically restore the cursor position after the trim?
Maybe wrapping the trim call between a `getpos` and `setpos` calls.

**Comment by johnfrankmorgan** [comment]
Hey @matteo-briani, sorry for such a big delay in getting back to you.

I don't actually use this plugin anymore as I've moved away from neovim. If you have an idea about how to go about implementing it, I'm happy to review a PR 😃

**Comment by adamcstephens** [comment]
It should be possible to move this logic into `trim()`:

```lua
local save_cursor = vim.fn.getpos(".")
require('whitespace-nvim').trim()
vim.fn.setpos(".", save_cursor)
```
