### ISSUE TITLE
Plugin broke

### ISSUE THREAD

**Issue by ivysochyn** [johnfrankmorgan/whitespace.nvim#9]
Hey, I recently moved from submodules to packer and spotted that with commit `904a82dbf6c25e414bd20690a6d3cd9064eb5303`, the trailing whitespaces highlighting stopped working for me. Could you assist in resolving this problem? For now keeping this plugin as a submodule to stay on a working version :/

**Comment by johnfrankmorgan** [comment]
Hey @ivysochyn, did you resolve this?

**Comment by ivysochyn** [comment]
I apologize; yesterday, I was experimenting with different plugins and, by mistake, created an Issue in the wrong repository. Thanks for the quick reaction :)

**Comment by johnfrankmorgan** [comment]
No problem, easily done! 😄
